#!/usr/bin/env checkio --domain=py run double-substring




def double_substring(line):
	dct={'':0}#default Value
	for i in range(0,int(len(line)/2+1)):
		for n in range(0,len(line)-i):
			pattern=(line[n:n+i+1])
			if line.count(pattern)>1:
				dct[pattern]=line.count(pattern)

	mostCommonKey=max(dct.items(),key=lambda x: x[1])[0]    #extra
	MostCommonKeyVal=max(dct.items(),key=lambda x: x[1])[1]    #extra
	longKey=max(dct.keys(),key=len)
	print(mostCommonKey)    #extra
	print(MostCommonKeyVal)    #extra
	print(longKey)
	return len(longKey)


line='sjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzx'
double_substring(line)

'''

if __name__ == '__main__':
	#These "asserts" using only for self-checking and not necessary for auto-testing
	assert double_substring('aa') == 3, "First"
	print('"Run" is good. How is "Check"?')

'''

import re

def double_substring(line):
    return max(map(len, re.findall(r'(?=(.*).*\1)', line)))


line='sjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzxsjnclkjsncdlkjncdlkjsanlckjndslkjcndsaljcouewourtwtwmxlkmslkcmclckclkjizuuyuzx'

double_substring(line)